### PR TITLE
Add support for server events websockets

### PR DESCRIPTION
**Pull request by leonekmi**

### CODE REVIEW

**Comment by toomuchio** [comment]
Are you just being pedantic or does that actually effect it working? I've had webhooks working fine with it being lower-case.

**Comment by leonekmi** [comment]
I have 502 without those extra settings on my install.

**Comment by toomuchio** [comment]
Ah I didn't see the other stuff when I made that first comment on mobile atm, makes sense!

First merge and commit of the year, happy new year and thanks for the fix ;)

**Comment by leonekmi** [comment]
I'm not in 2019 (from Europe), but happy new year also :tada: !

**Comment by gdob** [comment]
What does this accomplish? I’ve had it working fine without these changes. Am I missing something out?

**Pull request merged**
